niceplaces = ['Japan', 'Canada', 'Dubai', 'Spain', 'Paris', 'China']
print(niceplaces)
print(sorted(niceplaces))
print(niceplaces)
print(sorted(niceplaces,reverse = True))
print(niceplaces)
niceplaces.reverse()
print(niceplaces)
niceplaces.reverse()
print(niceplaces)
niceplaces.sort()
print(niceplaces)
niceplaces.sort(reverse=True)
print(niceplaces)
